kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dataease-custom-drivers-pvc
spec:
  accessModes:
    - {{.Values.dataPersistence.accessModes}}
  resources:
    requests:
      storage: {{.Values.dataPersistence.size}}
  storageClassName: {{.Values.common.storageClass}}
